[pytest]
; Эта настройка добавляет корневую папку проекта в sys.path
; Благодаря этому Python находит ваши модули pages, locators и т.д.
pythonpath = .

filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning

addopts =
    -v -s